### ISSUE TITLE
[Question] How can i use custom react package?

### ISSUE THREAD

**Issue by raphaelclh** [formio/react#340]
How can i implement a word highlighting package or function such as https://github.com/bonafideduck/react-highlight-within-textarea, together with form.io text area?

**Comment by alexandraRamanenka** [comment]
You can achieve something like this only by direct nodes manipulation since react-formio Form is only a wrapper for the core formiojs components. 
To select the component root node use the following selector pattern `.formio-component-${componentAPIKey}` 
To select the input of the component use `.formio-component-${componentAPIKey} [ref='input']`

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!
